package cmd

import "fmt"

func Help() {
	fmt.Println("MiniGit - A Minimal Git-Like Version Control System")
	fmt.Println()
	fmt.Println("Usage:")
	fmt.Println("  minigit <command> [arguments]")
	fmt.Println()
	fmt.Println("Available Commands:")
	fmt.Println("  init             Initialize a new minigit repository")
	fmt.Println("  add <file...>    Add files to the staging area (use '.' for all)")
	fmt.Println("  commit -m <msg>  Commit staged changes with a message")
	fmt.Println("  branch [options] Manage branches:")
	fmt.Println("    branch                    List all branches")
	fmt.Println("    branch <name>             Create a new branch")
	fmt.Println("    branch -d <name>          Delete branch (safe)")
	fmt.Println("    branch -D <name>          Delete branch (force)")
	fmt.Println("    branch -m <old> <new>     Rename branch")
	fmt.Println("  checkout <name>  Switch to specified branch")
	fmt.Println("  diff             Show changes between working dir and index")
	fmt.Println("  status           Show current status of working directory")
	fmt.Println("  log              Show commit history")
	fmt.Println("  reset <hash>     Reset working directory to a specific commit")
	fmt.Println("  merge <branch>   Merge specified branch into current one")
	fmt.Println("  rebase <branch>  Reapply commits from current branch onto another")
	fmt.Println("    rebase --abort           Abort current rebase operation")
	fmt.Println("  stash            Stash current changes")
	fmt.Println("    stash                    Stash changes with default message")
	fmt.Println("    stash <message>          Stash changes with custom message")
	fmt.Println("    stash pop                Apply and remove latest stash")
	fmt.Println("    stash list               List all stashes")
	fmt.Println("  revert <hash>    Revert a specific commit (like undo)")
	fmt.Println("  rm [options]     Remove files:")
	fmt.Println("    rm <file>                Remove file from working dir and index")
	fmt.Println("    rm --cached <file>       Remove file from index only")
	fmt.Println("    rm -f <file>             Force removal")
	fmt.Println("  abort            Abort current merge or rebase operation")
	fmt.Println()
	fmt.Println("Configuration:")
	fmt.Println("  set-user [name]  Set username for commits")
	fmt.Println("  get-user         Show current username")
	fmt.Println()
	fmt.Println("Use 'minigit <command>' for more information on a command.")
}
